name: test

on:
    workflow_dispatch:
permissions:
    contents: write

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: url-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Receiver Repo
        uses: actions/checkout@v4
        with:
          repository: Jahirul-Islam2347084327/API-Tool-K8-Infrastructure
          token: ${{ secrets.GH_PAT }}

      - name: Update Kubernetes manifest
        env:
          ECR_REGISTRY: test
        run: |
          sed -i "s|image:.*|image: $ECR_REGISTRY/url-app:${{ github.sha }}|g" ./kubernetes/manifest/deployment.yaml
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add kubernetes/manifest/deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          
          git push origin HEAD:main